-- Bo bai tap 'Permutations, Arrangements, Combinations, and Newton's Binomial Theorem'
-- INSERT OR REPLACE theo id nen chay lai bao nhieu lan cung an toan
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('perm_cat', 'Permutations of “CAT”', 100, '6', '<p>Calculate the number of distinct permutations of the letters in the word “CAT”.</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('perm_book', 'Permutations of “BOOK”', 100, '12', '<p>Calculate the number of distinct permutations of the letters in the word “BOOK”.</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('comb_committee_3of10', 'Choosing a Committee of 3', 100, '120', '<p>Find the number of ways to choose 3 students from a class of 10 to form a committee.</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('binom_coeff_x3_xy7', 'Coefficient of x³ in (x + y)⁷', 100, '35', '<p>Find the coefficient of \(x^3\) in the expansion of \((x + y)^7\).</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('stars_bars_nonneg_5', 'Non-negative Solutions to x₁+x₂+x₃=5', 100, '21', '<p>Determine the number of non-negative integer solutions to the equation \(x_1 + x_2 + x_3 = 5\).</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('pigeonhole_birth_month', 'Birth Month Pigeonhole', 100, '13', '<p>In a group of 50 people, how many people must be selected to guarantee that at least 2 share the same birth month (assuming 12 months)?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('arrange_4_books', 'Arranging 4 Distinct Books', 100, '24', '<p>Calculate the number of ways to arrange 4 distinct books on a shelf.</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('binom_coeff_x2y4_xy6', 'Coefficient of x²y⁴ in (x + y)⁶', 100, '15', '<p>Find the coefficient of \(x^2y^4\) in the expansion of \((x + y)^6\).</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('balls_boxes_no_empty', 'Balls into Boxes (No Box Empty)', 100, '150', '<p>In how many ways can 5 different balls be distributed into 3 different boxes such that no box is empty?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('coin_flips_6_heads', 'Coin Flips with Exactly 6 Heads', 100, '210', '<p>A coin is flipped 10 times. How many sequences contain exactly 6 heads?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sum_binom_coeff_n5', 'Sum of Binomial Coefficients (n = 5)', 100, '32', '<p>Calculate the value of \(\sum_{k=0}^{5} \binom{5}{k}\).</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('positive_int_solutions_4var', 'Positive Integer Solutions (4 Variables)', 100, '84', '<p>How many positive integer solutions are there to \(x_1 + x_2 + x_3 + x_4 = 10\)?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('perm_mississippi', 'Permutations of “MISSISSIPPI”', 100, '34650', '<p>Find the number of permutations of the word “MISSISSIPPI”.</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('binom_coeff_x4_1x10', 'Coefficient of x⁴ in (1 + x)¹⁰', 100, '210', '<p>What is the coefficient of \(x^4\) in the expansion of \((1 + x)^{10}\)?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('pigeonhole_mod7', 'Pigeonhole: Same Remainder mod 7', 100, '8', '<p>In a set of 100 integers, what is the minimum number of integers one must select to guarantee that two of them have the same remainder when divided by 7?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('candies_min_one_each', 'Distributing Candies with a Minimum Each', 100, '10', '<p>Calculate the number of ways to distribute 6 identical candies to 3 distinct children such that each child gets at least 1 candy.</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('functions_4_objects_2_boxes', 'Functions from 4 Objects to 2 Boxes', 100, '16', '<p>If n distinct objects are placed into k distinct boxes, how many ways can this be done if \(n = 4\) and \(k = 2\)?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sum_coeff_2x_3y_5', 'Sum of Coefficients in (2x − 3y)⁵', 100, '-1', '<p>Find the sum of the coefficients in the expansion of \((2x - 3y)^5\).</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('committee_2men_2women', 'Committee with Exactly 2 Men and 2 Women', 100, '100', '<p>A committee of 4 people is to be formed from 5 men and 5 women. How many ways can this be done if the committee must contain exactly 2 men and 2 women?</p>', 'answer', '');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('prove_symmetry_identity', 'Proving C(n,k) = C(n, n−k)', 100, '15', '<p>Prove that \(\binom{n}{k} = \binom{n}{n-k}\) for \(n = 6\), \(k = 2\) and provide the numerical result.</p>', 'answer', '');