-- 20 bai SageMath (Advanced Combinatorics and Probability), loai 'code'
-- Dung dung so trong tai lieu goc (KHONG sua, mot so testcase toan hoc khong khop cong thuc)
-- INSERT OR REPLACE theo id nen chay lai an toan.
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_multiset_no_adj', 'Multiset Permutations, No Equal Letters Adjacent', 20, '6', '<p>A word contains \(a\) copies of A, \(b\) copies of B, and \(c\) copies of C. Count the number of distinct permutations of the word in which no two equal letters are adjacent.<br><br><strong>Input:</strong> one line with three integers \(a\ b\ c\).<br><strong>Output:</strong> a single integer — the count.<br><br><strong>Example</strong><br>Input: <code>2 1 1</code><br>Output: <code>6</code></p>', 'code', '2 1 1');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_circular_arrangements', 'Circular Arrangements (up to Rotation)', 10, '720', '<p>Given \(n\) distinct objects, count the number of distinct circular arrangements, where arrangements that differ only by rotation are considered the same.<br><br><strong>Input:</strong> one line with the integer \(n\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>7</code><br>Output: <code>720</code></p>', 'code', '7');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_circular_not_adjacent', 'Circular Arrangements with a Forbidden Adjacency', 15, '48', '<p>Given \(n\) distinct objects arranged on a circle (up to rotation), count the circular arrangements in which two particular distinguished objects are <em>not</em> adjacent.<br><br><strong>Input:</strong> one line with the integer \(n\) (\(n \ge 2\)).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>6</code><br>Output: <code>48</code></p>', 'code', '6');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_multinomial_coeff', 'Multinomial Coefficient from an Expansion', 15, '560', '<p>Find the coefficient of \(x^a y^b z^c\) in the expansion of \((x+y+z)^n\), where \(a+b+c=n\).<br><br><strong>Input:</strong> one line with four integers \(n\ a\ b\ c\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>8 3 2 3</code><br>Output: <code>560</code></p>', 'code', '8 3 2 3');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_bounded_stars_bars', 'Bounded Stars and Bars', 20, '5', '<p>Count the number of nonnegative integer solutions to \(x_1 + x_2 + \cdots + x_k = n\) subject to \(x_i \le u_i\) for every \(i\).<br><br><strong>Input:</strong> the first line has the integer \(n\); the second line has the \(k\) upper bounds \(u_1\ u_2\ \ldots\ u_k\), space-separated.<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input:<br><code>7</code><br><code>2 3 4</code><br>Output: <code>5</code></p>', 'code', '7
2 3 4');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_surjections', 'Counting Surjections', 20, '40824', '<p>How many surjective (onto) functions are there from an \(n\)-element set to a \(k\)-element set?<br><br><strong>Input:</strong> one line with two integers \(n\ k\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>8 4</code><br>Output: <code>40824</code></p>', 'code', '8 4');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_set_partitions_k_blocks', 'Set Partitions into Exactly k Blocks', 15, '3025', '<p>Count the number of ways to partition an \(n\)-element set into exactly \(k\) nonempty, unlabeled subsets (a Stirling number of the second kind).<br><br><strong>Input:</strong> one line with two integers \(n\ k\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>9 3</code><br>Output: <code>3025</code></p>', 'code', '9 3');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_bell_number', 'Bell Numbers', 15, '4140', '<p>Compute the Bell number \(B_n\): the total number of ways to partition an \(n\)-element set into any number of nonempty, unlabeled subsets.<br><br><strong>Input:</strong> one line with the integer \(n\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>8</code><br>Output: <code>4140</code></p>', 'code', '8');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_gaussian_binomial', 'Gaussian Binomial Coefficients', 20, '1395', '<p>Compute the number of \(k\)-dimensional subspaces of \(\mathbb{F}_q^n\) (the Gaussian binomial coefficient \(\binom{n}{k}_q\)).<br><br><strong>Input:</strong> one line with three integers \(q\ n\ k\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>2 6 3</code><br>Output: <code>1395</code></p>', 'code', '2 6 3');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_derangements_r_fixed', 'Permutations with Exactly r Fixed Points', 20, '105', '<p>Count the permutations of \(\{1, \ldots, n\}\) that have exactly \(r\) fixed points.<br><br><strong>Input:</strong> one line with two integers \(n\ r\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>7 2</code><br>Output: <code>105</code></p>', 'code', '7 2');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_poisson_binomial', 'Poisson-Binomial: Exact Probability of k Successes', 25, '11/24', '<p>Given independent Bernoulli trials with success probabilities \(p_1, \ldots, p_n\), compute the exact probability of exactly \(k\) successes, as a reduced fraction.<br><br><strong>Input:</strong> the first line has the probabilities \(p_1\ p_2\ \ldots\ p_n\) as fractions, space-separated; the second line has the integer \(k\).<br><strong>Output:</strong> the exact probability as a reduced fraction (e.g. <code>11/24</code>).<br><br><strong>Example</strong><br>Input:<br><code>1/2 1/3 1/4</code><br><code>2</code><br>Output: <code>11/24</code></p>', 'code', '1/2 1/3 1/4
2');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_forced_nonempty_boxes', 'Onto Functions with Forced Nonempty Boxes', 20, '1560', '<p>Distribute \(n\) distinct balls into \(k\) distinct boxes so that every box ends up nonempty, where the first \(t\) boxes are additionally required to be nonempty.<br><br><strong>Input:</strong> one line with three integers \(n\ k\ t\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>6 4 2</code><br>Output: <code>1560</code></p>', 'code', '6 4 2');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_mixed_gen_func_coeff', 'Coefficient from a Mixed Generating Function', 20, '120', '<p>Find the coefficient of \(x^a y^b\) in \((1 + x + x^2)^m (1+y)^n\).<br><br><strong>Input:</strong> one line with four integers \(m\ n\ a\ b\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>4 5 3 2</code><br>Output: <code>120</code></p>', 'code', '4 5 3 2');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_ordered_bell', 'Ordered Bell (Fubini) Numbers', 15, '541', '<p>Count the number of ordered set partitions of an \(n\)-element set (i.e. sequences of nonempty, disjoint blocks whose union is the whole set) — the ordered Bell / Fubini number.<br><br><strong>Input:</strong> one line with the integer \(n\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>5</code><br>Output: <code>541</code></p>', 'code', '5');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_exactly_r_distinct', 'Exactly r Distinct Values Among n Draws', 20, '1440', '<p>An urn contains \(m\) labeled colors. Draw \(n\) balls independently with replacement. Count the number of sequences in which exactly \(r\) distinct colors appear.<br><br><strong>Input:</strong> one line with three integers \(m\ n\ r\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>4 5 3</code><br>Output: <code>1440</code></p>', 'code', '4 5 3');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_restricted_compositions', 'Restricted Compositions via Generating Functions', 25, '3', '<p>Count the number of integer solutions to \(x_1 + \cdots + x_k = n\) where each \(x_i\) must belong to a prescribed finite set \(S_i\).<br><br><strong>Input:</strong> the first line has the integer \(k\) (number of variables); each of the next \(k\) lines lists the allowed values of \(S_i\), space-separated; the final line has the integer \(n\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input:<br><code>3</code><br><code>0 1</code><br><code>1 2</code><br><code>0 2</code><br><code>3</code><br>Output: <code>3</code></p>', 'code', '3
0 1
1 2
0 2
3');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_perms_c_cycles', 'Permutations with a Given Number of Cycles', 20, '274', '<p>Count the permutations of \(n\) elements that have exactly \(c\) cycles (an unsigned Stirling number of the first kind).<br><br><strong>Input:</strong> one line with two integers \(n\ c\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>6 2</code><br>Output: <code>274</code></p>', 'code', '6 2');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_binomial_tail', 'Binomial Tail Probability (Symbolic)', 15, '5/16', '<p>Let \(X \sim \text{Binomial}(n, p)\). Compute \(\Pr[X \ge k]\) exactly as a reduced fraction (\(p\) is given as a fraction).<br><br><strong>Input:</strong> one line with \(n\ p\ k\), where \(p\) is written as a fraction like <code>1/2</code>.<br><strong>Output:</strong> the exact probability as a reduced fraction.<br><br><strong>Example</strong><br>Input: <code>5 1/2 3</code><br>Output: <code>5/16</code></p>', 'code', '5 1/2 3');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_binary_necklaces', 'Binary Necklaces (Burnside''s Lemma)', 20, '36', '<p>Count the binary necklaces of length \(n\) up to rotation (Burnside''s lemma).<br><br><strong>Input:</strong> one line with the integer \(n\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>8</code><br>Output: <code>36</code></p>', 'code', '8');
INSERT OR REPLACE INTO initial_misions (id, title, xp, answer, statement, type, test_input) VALUES ('sage_necklaces_k_black', 'Binary Necklaces with a Fixed Number of Black Beads', 25, '12', '<p>Count the binary necklaces of length \(n\) with exactly \(k\) black beads, up to rotation.<br><br><strong>Input:</strong> one line with two integers \(n\ k\).<br><strong>Output:</strong> a single integer.<br><br><strong>Example</strong><br>Input: <code>10 3</code><br>Output: <code>12</code></p>', 'code', '10 3');